# Generated by Django 4.2.27 on 2026-04-25 22:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40)),
                ('order_date', models.DateField()),
                ('required_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('channel', models.CharField(choices=[('website', 'Website'), ('phone', 'Phone'), ('in_store', 'In store'), ('social', 'Social')], default='website', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loyalty_points_earned', models.PositiveIntegerField(default=0)),
                ('loyalty_points_redeemed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-order_date', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='BakeryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakeops_order_items', to='cakes.cake')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bakeops.bakeryorder')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakeops_order_items', to='cakes.cakevariant')),
            ],
            options={
                'ordering': ['order', 'cake'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_repeat_customer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Millilitre'), ('l', 'Litre'), ('each', 'Each')], default='g', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('current_stock_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('reorder_level_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=80)),
                ('production_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-production_date', 'batch_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produced_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('failed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bakeops.productionbatch')),
            ],
            options={
                'ordering': ['batch', 'recipe'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('legal_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='United Kingdom', max_length=80)),
                ('currency', models.CharField(default='GBP', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_date', models.DateField()),
                ('reason', models.CharField(choices=[('expiry', 'Expiry'), ('overproduction', 'Overproduction'), ('damage', 'Damage'), ('cancellation', 'Cancellation'), ('recipe_error', 'Recipe error'), ('quality_issue', 'Quality issue'), ('other', 'Other')], max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('batch_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='bakeops.productionbatchline')),
                ('cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakeops_waste_records', to='cakes.cake')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='bakeops.ingredient')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakeops_waste_records', to='cakes.cakevariant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['-waste_date', 'reason'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('lead_time_days', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('baker', 'Baker'), ('analyst', 'Analyst')], default='baker', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakeops_staff_profiles', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['workspace', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('expected_yield_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('labour_minutes', models.PositiveIntegerField(default=0)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakeops_recipes', to='cakes.cake')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakeops_recipes', to='cakes.cakevariant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['cake', 'name'],
                'unique_together': {('workspace', 'cake', 'variant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productionbatchline',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lines', to='bakeops.recipe'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='planned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_batches', to='bakeops.staffmember'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='bakeops.workspace'),
        ),
        migrations.CreateModel(
            name='OccasionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasion_types', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('lifetime_points_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_points_redeemed', models.PositiveIntegerField(default=0)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bakeops_loyalty_account', to='bakeops.customer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['customer__full_name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='bakeops.supplier'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='bakeops.workspace'),
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity_orders', models.PositiveIntegerField(default=10)),
                ('booked_orders', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['slot_date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='bakeops.workspace'),
        ),
        migrations.CreateModel(
            name='CakeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('review_date', models.DateField()),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakeops_reviews', to='cakes.cake')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake_reviews', to='bakeops.customer')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakeops_reviews', to='cakes.cakevariant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_reviews', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['-review_date', 'cake'],
            },
        ),
        migrations.AddField(
            model_name='bakeryorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakery_orders', to='bakeops.customer'),
        ),
        migrations.AddField(
            model_name='bakeryorder',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakery_orders', to='bakeops.deliveryslot'),
        ),
        migrations.AddField(
            model_name='bakeryorder',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakery_orders', to='bakeops.occasiontype'),
        ),
        migrations.AddField(
            model_name='bakeryorder',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakery_orders', to='bakeops.workspace'),
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=12)),
                ('waste_factor_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='bakeops.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bakeops.recipe')),
            ],
            options={
                'ordering': ['recipe', 'ingredient'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productionbatch',
            unique_together={('workspace', 'batch_code')},
        ),
        migrations.CreateModel(
            name='IngredientLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=80)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='bakeops.ingredient')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_lots', to='bakeops.workspace')),
            ],
            options={
                'ordering': ['expiry_date', 'ingredient'],
                'unique_together': {('workspace', 'lot_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('workspace', 'email')},
        ),
        migrations.CreateModel(
            name='BatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='bakeops.productionbatchline')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='bakeops.bakeryorderitem')),
            ],
            options={
                'ordering': ['batch_line', 'order_item'],
                'unique_together': {('batch_line', 'order_item')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bakeryorder',
            unique_together={('workspace', 'order_number')},
        ),
    ]
